import { useEffect, useState } from 'react'
import { Card, Button, ConfirmDialog, EmptyState, Field, Modal, Spinner, useToast, Toast } from '../components/UI'
import { estudiantesApi, modulosApi, docentesApi } from '../services/api'
import { specialtyLabel } from '../utils/academic'

function useCrud(api, initial, label) { const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [editing,setEditing]=useState(null);const [removeId,setRemoveId]=useState(null);const {toast,notify,clear}=useToast();const load=()=>{setLoading(true);api.list().then(setItems).catch(e=>notify(e.message,'error')).finally(()=>setLoading(false))};useEffect(load,[]);const save=async(form)=>{setSaving(true);try{if(editing) await api.update(editing.id,form);else await api.create(form);notify(`${label} ${editing?'actualizado':'registrado'} correctamente.`);setEditing(null);load()}catch(e){notify(e.message,'error')}finally{setSaving(false)}};const del=async()=>{try{await api.remove(removeId);notify(`${label} eliminado correctamente.`);setRemoveId(null);load()}catch(e){notify(e.message,'error')}};return {items,loading,saving,editing,setEditing,removeId,setRemoveId,save,del,toast,clear}}

export function Students(){const c=useCrud(estudiantesApi,{},'Estudiante');const [q,setQ]=useState('');const [filters,setFilters]=useState({año:'',especialidad:'',seccion:''});const filtered=c.items.filter(x=>`${x.nombres} ${x.apellidos}`.toLowerCase().includes(q.toLowerCase())&&(!filters.año||x.año===filters.año)&&(!filters.especialidad||x.especialidad===filters.especialidad)&&(!filters.seccion||x.seccion===filters.seccion));return <><PageHead title="Estudiantes" text="Administra el padrón académico de estudiantes." action={()=>c.setEditing({nombres:'',apellidos:'',año:'',especialidad:'Desarrollo de Software',seccion:'A'})}/><Card><Toolbar q={q} setQ={setQ} filters={filters} setFilters={setFilters} items={c.items}/>{c.loading?<Loading/>:filtered.length?<StudentTable items={filtered} onEdit={c.setEditing} onDelete={c.setRemoveId}/>:<EmptyState title="No se encontraron estudiantes" text="Ajusta los filtros o agrega un estudiante."/>}</Card><StudentModal editing={c.editing} setEditing={c.setEditing} onSave={c.save} loading={c.saving}/><ConfirmDialog open={!!c.removeId} message="Esta acción eliminará el registro y puede afectar sus avances relacionados." onCancel={()=>c.setRemoveId(null)} onConfirm={c.del}/><Toast toast={c.toast} onClose={c.clear}/></>}
function StudentTable({items,onEdit,onDelete}){return <div className="table-wrap"><table><thead><tr><th>Estudiante</th><th>Año</th><th>Especialidad</th><th>Sección</th><th>Estado</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.apellidos}, {x.nombres}</strong></td><td>{x.año}</td><td>{specialtyLabel(x.especialidad)}</td><td>{x.seccion}</td><td><span className={`status ${x.activo?'active':'inactive'}`}>{x.activo?'Activo':'Inactivo'}</span></td><td className="actions"><button onClick={()=>onEdit(x)}>Editar</button><button className="danger-link" onClick={()=>onDelete(x.id)}>Eliminar</button></td></tr>)}</tbody></table></div>}
function Toolbar({q,setQ,filters,setFilters,items}){const vals=(key)=>[...new Set(items.map(x=>x[key]).filter(Boolean))];return <div className="toolbar"><input className="search" placeholder="⌕  Buscar estudiante…" value={q} onChange={e=>setQ(e.target.value)}/><select value={filters.año} onChange={e=>setFilters({...filters,año:e.target.value})}><option value="">Todos los años</option>{vals('año').map(v=><option key={v}>{v}</option>)}</select><select value={filters.especialidad} onChange={e=>setFilters({...filters,especialidad:e.target.value})}><option value="">Especialidad</option>{vals('especialidad').map(v=><option key={v} value={v}>{specialtyLabel(v)}</option>)}</select><select value={filters.seccion} onChange={e=>setFilters({...filters,seccion:e.target.value})}><option value="">Sección</option>{vals('seccion').map(v=><option key={v}>{v}</option>)}</select></div>}
function StudentModal({editing,setEditing,onSave,loading}){const [f,setF]=useState(editing||{});useEffect(()=>setF(editing||{}),[editing]);if(!editing)return null;return <Modal open title={editing.id?'Editar estudiante':'Nuevo estudiante'} onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={e=>{e.preventDefault();onSave({...f,activo:f.activo!==false})}}><Field label="Nombres"><input value={f.nombres||''} onChange={e=>setF({...f,nombres:e.target.value})} required/></Field><Field label="Apellidos"><input value={f.apellidos||''} onChange={e=>setF({...f,apellidos:e.target.value})} required/></Field><Field label="Año"><select value={f.año||''} onChange={e=>setF({...f,año:e.target.value})} required><option value="">Selecciona</option><option>1</option><option>2</option><option>3</option></select></Field><Field label="Especialidad"><select value={f.especialidad||''} onChange={e=>setF({...f,especialidad:e.target.value})} required><option value="">Selecciona</option>{Object.entries({ADM:'Administrativo Contable',AUTO:'Mantenimiento Automotriz',SAL:'Salud',SOFT:'Desarrollo de Software',TURISMO:'Servicios Turísticos',GRAL:'General'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Sección"><input value={f.seccion||''} onChange={e=>setF({...f,seccion:e.target.value})} required/></Field><div className="modal-actions full"><Button variant="ghost" onClick={()=>setEditing(null)}>Cancelar</Button><Button type="submit" loading={loading}>Guardar</Button></div></form></Modal>}

export function Modules(){const c=useCrud(modulosApi,{},'Módulo');const [q,setQ]=useState('');const filtered=c.items.filter(x=>`${x.codigo} ${x.nombre}`.toLowerCase().includes(q.toLowerCase()));return <><PageHead title="Módulos" text="Configura los módulos académicos por año y especialidad." action={()=>c.setEditing({codigo:'',nombre:'',año:'',especialidad:'Desarrollo de Software',activo:true})}/><Card><div className="toolbar"><input className="search" placeholder="⌕  Buscar módulo…" value={q} onChange={e=>setQ(e.target.value)}/></div>{c.loading?<Loading/>:filtered.length?<div className="table-wrap"><table><thead><tr><th>Código</th><th>Módulo</th><th>Año</th><th>Especialidad</th><th>Estado</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><span className="code-chip">{x.codigo}</span></td><td><strong>{x.nombre}</strong></td><td>{x.año}</td><td>{specialtyLabel(x.especialidad)}</td><td><span className={`status ${x.activo?'active':'inactive'}`}>{x.activo?'Activo':'Inactivo'}</span></td><td className="actions"><button onClick={()=>c.setEditing(x)}>Editar</button><button className="danger-link" onClick={()=>c.setRemoveId(x.id)}>Eliminar</button></td></tr>)}</tbody></table></div>:<EmptyState title="No hay módulos" text="Agrega los módulos reales de la institución."/>}</Card><ModuleModal editing={c.editing} setEditing={c.setEditing} onSave={c.save} loading={c.saving}/><ConfirmDialog open={!!c.removeId} message="Se eliminará el módulo seleccionado." onCancel={()=>c.setRemoveId(null)} onConfirm={c.del}/><Toast toast={c.toast} onClose={c.clear}/></>}
function ModuleModal({editing,setEditing,onSave,loading}){const [f,setF]=useState(editing||{});useEffect(()=>setF(editing||{}),[editing]);if(!editing)return null;return <Modal open title={editing.id?'Editar módulo':'Nuevo módulo'} onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={e=>{e.preventDefault();onSave({...f,activo:f.activo!==false})}}><Field label="Código"><input value={f.codigo||''} onChange={e=>setF({...f,codigo:e.target.value})} required/></Field><Field label="Nombre del módulo"><input value={f.nombre||''} onChange={e=>setF({...f,nombre:e.target.value})} required/></Field><Field label="Año"><select value={f.año||''} onChange={e=>setF({...f,año:e.target.value})} required><option value="">Selecciona</option><option>1</option><option>2</option><option>3</option></select></Field><Field label="Especialidad"><select value={f.especialidad||''} onChange={e=>setF({...f,especialidad:e.target.value})} required><option value="">Selecciona</option>{Object.entries({ADM:'Administrativo Contable',AUTO:'Mantenimiento Automotriz',SAL:'Salud',SOFT:'Desarrollo de Software',TURISMO:'Servicios Turísticos',GRAL:'General'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Estado"><select value={f.activo===false?'false':'true'} onChange={e=>setF({...f,activo:e.target.value==='true'})}><option value="true">Activo</option><option value="false">Inactivo</option></select></Field><div className="modal-actions full"><Button variant="ghost" onClick={()=>setEditing(null)}>Cancelar</Button><Button type="submit" loading={loading}>Guardar</Button></div></form></Modal>}

export function Teachers(){
  const c=useCrud(docentesApi,{},'Docente')
  const [q,setQ]=useState('')
  const [provisioning,setProvisioning]=useState(false)
  const [credentials,setCredentials]=useState(null)
  const filtered=c.items.filter(x=>`${x.nombre} ${x.apellido} ${x.codigo_siges||''} ${x.usuario||''}`.toLowerCase().includes(q.toLowerCase()))
  const {notify}=c
  async function provision(){
    setProvisioning(true)
    try{
      const teachers = (await import('../data/teachers2026')).TEACHERS_2026.filter(t=>t.codigo_siges!=='039482598')
      const result=await docentesApi.provision2026(teachers)
      setCredentials(result.credentials||[])
      notify(`Se prepararon ${result.total||0} cuentas docentes.`)
    }catch(e){ notify(e.message||'No fue posible preparar las cuentas.','error') }
    finally{setProvisioning(false)}
  }
  return <>
    <PageHead title="Docentes" text="Usuarios y accesos docentes precargados según la asignación docente 2026." action={provision} actionLabel={provisioning?'Procesando…':'Preparar cuentas 2026'}/>
    <Card><div className="toolbar"><input className="search" placeholder="⌕  Buscar por nombre o usuario SIGES…" value={q} onChange={e=>setQ(e.target.value)}/></div>{c.loading?<Loading/>:filtered.length?<div className="table-wrap"><table><thead><tr><th>Docente</th><th>Usuario SIGES</th><th>Acceso</th><th>Estado</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{x.nombre} {x.apellido}</strong></td><td><span className="code-chip">{x.codigo_siges||x.usuario||'—'}</span></td><td>{x.codigo_siges==='039482598'?'Administrador':'Usuario docente'}</td><td><span className={`status ${x.activo?'active':'inactive'}`}>{x.activo?'Activo':'Inactivo'}</span></td><td className="actions"><button onClick={()=>c.setEditing(x)}>Editar</button></td></tr>)}</tbody></table></div>:<EmptyState title="No hay docentes" text="Ejecuta Preparar cuentas 2026 para cargar las cuentas de la asignación docente."/>}</Card>
    <TeacherCredentialsModal credentials={credentials} onClose={()=>setCredentials(null)}/>
    <TeacherModal editing={c.editing} setEditing={c.setEditing} onSave={c.save} loading={c.saving}/>
    <Toast toast={c.toast} onClose={c.clear}/>
  </>
}
function TeacherCredentialsModal({credentials,onClose}){
  if(!credentials)return null
  return <Modal open wide title="Credenciales docentes 2026" onClose={onClose}>
    <p className="modal-help">Las cuentas se crean sin correo de confirmación. Entrega a cada docente únicamente su usuario SIGES y su contraseña inicial.</p>
    <div className="table-wrap"><table><thead><tr><th>Docente</th><th>Usuario</th><th>Contraseña inicial</th></tr></thead><tbody>{credentials.map(c=><tr key={c.codigo_siges}><td>{c.nombre}</td><td><code>{c.codigo_siges}</code></td><td><code>{c.password}</code></td></tr>)}</tbody></table></div>
    <div className="modal-actions"><Button onClick={()=>window.print()}>Imprimir lista</Button><Button variant="ghost" onClick={onClose}>Cerrar</Button></div>
  </Modal>
}
function TeacherModal({editing,setEditing,onSave,loading}){const [f,setF]=useState(editing||{});useEffect(()=>setF(editing||{}),[editing]);if(!editing)return null;return <Modal open title="Editar docente" onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={e=>{e.preventDefault();onSave({nombre:f.nombre,apellido:f.apellido,activo:f.activo!==false})}}><Field label="Nombre"><input value={f.nombre||''} onChange={e=>setF({...f,nombre:e.target.value})} required/></Field><Field label="Apellido"><input value={f.apellido||''} onChange={e=>setF({...f,apellido:e.target.value})} /></Field><Field label="Usuario SIGES"><input value={f.codigo_siges||f.usuario||''} disabled /></Field><Field label="Estado"><select value={f.activo===false?'false':'true'} onChange={e=>setF({...f,activo:e.target.value==='true'})}><option value="true">Activo</option><option value="false">Inactivo</option></select></Field><div className="modal-actions full"><Button variant="ghost" type="button" onClick={()=>setEditing(null)}>Cancelar</Button><Button type="submit" loading={loading}>Guardar</Button></div></form></Modal>}
function PageHead({title,text,action,actionLabel='Nuevo'}){return <div className="page-intro"><div><p>Administración</p><h2>{title}</h2><span>{text}</span></div>{action&&<button className="btn btn-primary" onClick={action}>＋ {actionLabel}</button>}</div>}
function Loading(){return <div className="loading-panel"><Spinner/>Cargando…</div>}
